### ISSUE TITLE
[ci] ETQ dev, je souhaite avoir la CICD de paramétrée sur GitHub

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/lozen#3]
_Bloqué tant que {lozen} n'est pas sur GitHub_

## Validation - Client

- [x] La CICD est fonctionnelle sur le repo GitHub de {lozen}

## Dev - Tech

- [ ] Supprimer le fichier .gitlab-ci.yml de {lozen}
- [x] Mettre en place GitHhub Actions sur GitHub (il doit déployer le pkgdown via gh-pages)

#### Dans les scripts de deploy 

```
script = list(
          "echo \"Library path for packages :\" R_LIBS_USER",
          "mkdir -p R_LIBS_USER", "Rscript -e 'install.packages(c(\"git2r\"));install.packages(\"gitlabr\", repos = c(\"https://thinkr-open.r-universe.dev\", \"https://cloud.r-project.org\"))'",
          "Rscript -e 'options(remotes.git_credentials = git2r::cred_user_pass(\"gitlab-ci-token\", Sys.getenv(\"CI_JOB_TOKEN\")));remotes::install_git(\"https://forge.thinkr.fr/thinkr/thinkrverse/lozen\", build_vignettes = FALSE, ref = Sys.getenv(\"LOZEN_BRANCH\", unset = \"main\"))'",
          "Rscript -e 'lozen::deploy_connect_shiny(connect_url = Sys.getenv(\"CONNECT_URL\"),connect_user = Sys.getenv(\"CONNECT_USER\"),connect_api_token = Sys.getenv(\"CONNECT_TOKEN\"),app_name = Sys.getenv(\"APP_NAME\", unset = Sys.getenv(\"CI_PROJECT_NAME\")))'"
        )
```

#### Il faudra remplacer 
```
variables:
  GIT_DEPTH: 10
  REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
  R_LIBS_USER: "ci/lib"
  GITLAB_URL: "https://forge.thinkr.fr"
```
Mais seulement à la fin quand tout les forge seront changés
